### ISSUE TITLE
Remove warnings from all packages

### ISSUE THREAD

**Issue by rrnewton** [iu-parfunc/lvars#110]
Check off each when its main lib, tests, and benchmarks are warning-free:

 * [x] par-classes
 * [x] lvish
 * [x] par-transformers
 * [x] par-collections
 * [x] concurrent-skiplist
 * [x] tslogger

**Comment by DreamLinuxer** [comment]
06b89814a8cef97bddec8d9048140ea6ff64db3b

**Comment by DreamLinuxer** [comment]
58579eecf11c85705acd743483ff9f50e09ce2a6

**Comment by rrnewton** [comment]
As per our discussion it should be fine to just turn off the orphan instance warnings in `IVar.hs`.

**Comment by DreamLinuxer** [comment]
17cc74448ac019e4dea2537f8501cd54c754dd7b

**Comment by DreamLinuxer** [comment]
097e89e1ce56b9e7e20d2f6eb67ffb528ac3a4b8

**Comment by DreamLinuxer** [comment]
@rrnewton I think this one can be closed, please check.
