### ISSUE TITLE
Get mergesort running with the test-suite

### ISSUE THREAD

**Issue by rrnewton** [iu-parfunc/lvars#113]
After everything is green on our CI unit testing, mergesort should really be included as a test.

Currently it has its own cabal file.  But now that cabal has "benchmark" sections, it could be included as a benchmark of the top-level `par-transformers` cabal file.

**Comment by osa1** [comment]
I just implemented QuickCheck tests for this: https://github.com/iu-parfunc/lvars/commit/77a6a36fc38e733656c5a20345adaf4c3173465e#diff-1e8a7ec63946a27fbec1217374f65e69R26 unfortunately it's failing all the time. Looks like I have some debugging to do...

**Comment by osa1** [comment]
I fixed couple of bugs and implemented some tests(including QuickCheck test for sorting random vectors). Now only problem is making it running in travis.

**Comment by osa1** [comment]
`par-mergesort` is now ready but see #114.

**Comment by osa1** [comment]
This is done, Travis is green now.
