### ISSUE TITLE
Move modules around for a clearer organization of Control.LVish

### ISSUE THREAD

**Issue by rrnewton** [iu-parfunc/lvars#126]
Only these should be exposed to users:

 * `Control.LVish`
 * `Control.LVish.DeepFrz`
 * `Control.LVish.BulkRetry` -- But this one is still in beta.

All these should move underneath `Control/LVish/Internal/`:

 * `Control.LVish.Logical` -- reexported by Control.LVish, move to internal.
 * `Control.LVish.Types` -- ditto
 * `Control.LVish.Basics`   
 * `Control.LVish.Logging` 
 * `Control.LVish.SchedIdempotentInternal` -- This could move to `Control.LVish.Internal.SchedUtils`
 * `Internal.Control.LVish.SchedIdempotent` This could move to `Control.LVish.Internal.SchedIdempotent`
 * `Control.LVish.SchedClass` 
 * `Control.LVish.Unsafe` 

I think `Control/LVish/Internal.hs` itself can export what an LVar-implementor needs without any of the really really internal bits.  It should be the only point of external dependence.

**Comment by DreamLinuxer** [comment]
https://github.com/iu-parfunc/lvars/commit/1c701f586339047e05f45036d5ade77a3d3830b1
