### ISSUE TITLE
Split lvish package, create `lvish-extras`

### ISSUE THREAD

**Issue by rrnewton** [iu-parfunc/lvars#127]
The LVish packages is big.  This is a problem for incremental development, install times, testing, and dependencies management.

Proposal: `lvish` contain only LVars, Sets, Maps.  Everything else must go into a separate package.

Update the below list with the plan to move specific modules:

 * [ ] NatArray goes into `lvish-extras`, which gets rid of the problematic `bits-atomic` dependence.

**Comment by rrnewton** [comment]
@DreamLinuxer, did you ping the maintainer of bits-atomic about the problem on MacOS with newer clang?

**Comment by DreamLinuxer** [comment]
https://github.com/iu-parfunc/lvars/commit/aba3a5b4e7a91b0b48cd64ef2655baa4f4f7eafc
