### ISSUE TITLE
Combine CancelT ThreadID and CFut into one datatype.

### ISSUE THREAD

**Issue by rrnewton** [iu-parfunc/lvars#78]
They have a one-to-one correspondence currently, so returning them separately is not that useful.

**Comment by osa1** [comment]
This issue is quite old, and it seems like `CFut` has changed since then. Currently it's defined as:

```haskell
data CFut p s a = CFut (IVar p s CFutFate) (IVar p s a)
```

This isn't similar to `ThreadID`. Closing.
